# Generated by Django 5.2.6 on 2025-09-28 21:12

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("date_start", models.DateTimeField(blank=True, null=True)),
                ("date_end", models.DateTimeField(blank=True, null=True)),
                ("order", models.CharField(blank=True, max_length=256, null=True)),
                ("duration", models.CharField(blank=True, max_length=256, null=True)),
                ("time_event", models.CharField(blank=True, max_length=256, null=True)),
                ("status", models.CharField(blank=True, max_length=256, null=True)),
                ("url", models.CharField(blank=True, max_length=256, null=True)),
                ("created_by", models.CharField(blank=True, max_length=256, null=True)),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
