# Generated by Django 4.2.14 on 2025-09-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_verification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verification",
            old_name="instansi",
            new_name="address",
        ),
    ]
