# Generated by Django 5.2.6 on 2025-10-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_event_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="track",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together=set(),
        ),
    ]
