# Generated by Django 5.2.6 on 2025-10-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_track_options_alter_track_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="color",
        ),
    ]
