# Generated by Django 5.2.6 on 2025-10-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_track_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
