# Generated by Django 5.2.6 on 2025-10-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_track_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
