# Generated by Django 5.2.6 on 2025-10-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_track_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="track",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="app.track",
            ),
        ),
    ]
