# Generated by Django 5.2.6 on 2025-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_session_track"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
