# Generated by Django 5.2.6 on 2025-10-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_verification_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="session",
            name="event",
        ),
    ]
