# Generated by Django 5.2.6 on 2025-10-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_session_capacity_remove_session_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
