# Generated by Django 5.2.6 on 2025-10-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_session_end_time_alter_session_start_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendee",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_attendees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="SessionAttendee",
        ),
    ]
