# Generated by Django 5.2.6 on 2025-10-04 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_attendee_unique_together_alter_attendee_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendee",
            unique_together={("user", "event")},
        ),
    ]
